# Generated by Django 5.1.6 on 2025-07-06 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('buscador', 'Buscador de Empleo'), ('empresa', 'Empresa')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('actividad_economica', models.CharField(max_length=100)),
                ('tipo_persona', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('provincia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SistemaEmpleo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Buscador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SistemaEmpleo.usuario')),
            ],
        ),
    ]
