# Generated by Django 5.1.6 on 2025-07-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('buscador', 'Buscador de Empleo'), ('empresa', 'Empresa')], max_length=10)),
            ],
        ),
    ]
