# Generated by Django 5.2.1 on 2025-07-17 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaEmpleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('esta_activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='actividad_economica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaEmpleo.actividadeconomica'),
        ),
    ]
