# Generated by Django 5.1.6 on 2025-07-06 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaEmpleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buscador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SistemaEmpleo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('actividad_economica', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SistemaEmpleo.usuario')),
            ],
        ),
    ]
